### ISSUE TITLE
rocBLAS error: Tensile solution found, but kernel not found in any loaded module

### ISSUE THREAD

**Issue by littlewu2508** [justxi/rocm#184]
During pytorch forwarding a 4-layer CNN, MIOpen throw a rocBLAS error. The full output is:

```
MIOpen(HIP): Info [Handle] stream: 0, device_id: 0
MIOpen(HIP): Info [ForwardGetWorkSpaceSize] 
MIOpen(HIP): Info [HipCompilerVersionImpl] 4.0.20514
MIOpen(HIP): Info [AmdRocmMetadataVersionDetect] ROCm MD version AMDHSA_COv3, MIOpen version 2.9.0.0
MIOpen(HIP): Info [FindSolutionImpl] ConvBinWinogradRxSf2x3 (db access disabled)
MIOpen(HIP): Info [GetPerformanceConfig] 60
MIOpen(HIP): Info [GetForwardSolutions] 
MIOpen(HIP): Info [Measure] Db::Prefetch time: 60.6177 ms
MIOpen(HIP): Info [FindConvFwdAlgorithm] requestAlgoCount = 1, workspace = 0
MIOpen(HIP): Info [GetForwardSolutions] 
MIOpen(HIP): Info [CompileForwardSolution] solver_id = ConvBinWinogradRxSf2x3
MIOpen(HIP): Info [FindSolutionImpl] ConvBinWinogradRxSf2x3
MIOpen(HIP): Info [FindSolutionImpl] Perf Db: record not found for: ConvBinWinogradRxSf2x3
MIOpen(HIP): Info [GetPerformanceConfig] 60
MIOpen(HIP): Info [FindConvFwdAlgorithm] miopenConvolutionFwdAlgoWinograd	1.22816	0
MIOpen(HIP): Info [FindConvFwdAlgorithm] FW Chosen Algorithm: ConvBinWinogradRxSf2x3 , 0, 1.22816
MIOpen(HIP): Info [ConvolutionForward] algo = 3, workspace = 0
MIOpen(HIP): Info [ForwardGetWorkSpaceSize] 
MIOpen(HIP): Info [FindSolutionImpl] ConvBinWinogradRxSf3x2 (not searchable)
MIOpen(HIP): Info [FindSolutionImpl] ConvBinWinogradRxSf2x3 (db access disabled)
MIOpen(HIP): Info [GetPerformanceConfig] 60
MIOpen(HIP): Info [FindSolutionImpl] ConvBinWinogradRxS (not searchable)
MIOpen(HIP): Info [GetForwardSolutions] 
MIOpen(HIP): Info [FindConvFwdAlgorithm] requestAlgoCount = 1, workspace = 0
MIOpen(HIP): Info [GetForwardSolutions] 
MIOpen(HIP): Info [CompileForwardSolution] solver_id = ConvBinWinogradRxSf2x3
MIOpen(HIP): Info [FindSolutionImpl] ConvBinWinogradRxSf2x3
MIOpen(HIP): Info [FindSolutionImpl] Perf Db: record not found for: ConvBinWinogradRxSf2x3
MIOpen(HIP): Info [GetPerformanceConfig] 60
MIOpen(HIP): Info [FindConvFwdAlgorithm] miopenConvolutionFwdAlgoWinograd	6.20624	0
MIOpen(HIP): Info [FindConvFwdAlgorithm] FW Chosen Algorithm: ConvBinWinogradRxSf2x3 , 0, 6.20624
MIOpen(HIP): Info [ConvolutionForward] algo = 3, workspace = 0
MIOpen(HIP): Info [ForwardGetWorkSpaceSize] 
MIOpen(HIP): Info [FindSolutionImpl] ConvBinWinogradRxSf3x2 (not searchable)
MIOpen(HIP): Info [FindSolutionImpl] ConvBinWinogradRxSf2x3 (db access disabled)
MIOpen(HIP): Info [GetPerformanceConfig] 60
MIOpen(HIP): Info [FindSolutionImpl] ConvBinWinogradRxS (not searchable)
MIOpen(HIP): Info [GetForwardSolutions] 
MIOpen(HIP): Info [FindConvFwdAlgorithm] requestAlgoCount = 1, workspace = 0
MIOpen(HIP): Info [GetForwardSolutions] 
MIOpen(HIP): Info [CompileForwardSolution] solver_id = ConvBinWinogradRxSf2x3
MIOpen(HIP): Info [FindSolutionImpl] ConvBinWinogradRxSf2x3
MIOpen(HIP): Info [FindSolutionImpl] Perf Db: record not found for: ConvBinWinogradRxSf2x3
MIOpen(HIP): Info [GetPerformanceConfig] 60
MIOpen(HIP): Info [FindConvFwdAlgorithm] miopenConvolutionFwdAlgoWinograd	5.20016	0
MIOpen(HIP): Info [FindConvFwdAlgorithm] FW Chosen Algorithm: ConvBinWinogradRxSf2x3 , 0, 5.20016
MIOpen(HIP): Info [ConvolutionForward] algo = 3, workspace = 0
MIOpen(HIP): Info [ForwardGetWorkSpaceSize] 
MIOpen(HIP): Info [FindSolutionImpl] ConvBinWinogradRxSf3x2 (not searchable)
MIOpen(HIP): Info [FindSolutionImpl] ConvBinWinogradRxSf2x3 (db access disabled)
MIOpen(HIP): Info [GetPerformanceConfig] 60
MIOpen(HIP): Info [FindSolutionImpl] ConvBinWinogradRxS (not searchable)
MIOpen(HIP): Info [GetForwardSolutions] 
MIOpen(HIP): Info [GetForwardSolutionsFallback] Fallback path, GEMM
MIOpen(HIP): Info [FindConvFwdAlgorithm] requestAlgoCount = 1, workspace = 324000
MIOpen(HIP): Info [GetForwardSolutions] 
MIOpen(HIP): Info [GetForwardSolutionsFallback] Fallback path, GEMM
MIOpen(HIP): Info [TryLoad] Find-db regenerating.

rocBLAS error: Tensile solution found, but exception thown for { a_type: "f32_r", b_type: "f32_r", c_type: "f32_r", d_type: "f32_r", compute_type: "f32_r", transA: 'N', transB: 'N', M: 600, N: 10, K: 135, alpha: 1, row_stride_a: 1, col_stride_a: 600, row_stride_b: 1, col_stride_b: 135, row_stride_c: 1, col_stride_c: 600, row_stride_d: 1, col_stride_d: 600, beta: 0, batch_count: 1, stride_a: 1, stride_b: 1, stride_c: 1, stride_d: 1, atomics_mode: atomics_allowed }
Kernel Cijk_Ailk_Bljk_SB_MT32x32x2_SE_APM1_AF0EM1_AF1EM1_AMAS2_ASBE01_ASCE01_ASEM1_BL0_DTL0_EPS0_FL0_GRVW4_GSU1_ISA000_IU1_K1_KLS_LPA0_LPB0_LDL1_LRVW4_MDA2_NLCA1_NLCB1_ONLL1_PBD0_PK0_PGR1_PLR1_RK0_SU32_SUM0_SUS256_SVW4_SNLL0_TT4_4_USFGRO0_VAW1_VS1_VW4_WG8_8_1_WGM1 not found in any loaded module.
This message will be only be displayed once, unless the ROCBLAS_VERBOSE_TENSILE_ERROR environment variable is set.
MIOpen Error: /tmp/portage/sci-libs/miopen-4.0.0-r1/work/MIOpen-rocm-4.0.0/src/gemm_v2.cpp:523: rocBlas error encountered
True
Traceback (most recent call last):
  File "test.py", line 12, in <module>
    output = net.forward(wave)
  File "~/waveform-analysis/CNN_Module.py", line 23, in forward
    x = leaky_relu(self.conv4(x))
  File "/opt/gentoo/usr/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/gentoo/usr/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 258, in forward
    return F.conv1d(input, self.weight, self.bias, self.stride,
RuntimeError: miopenStatusInternalError
```

**Comment by littlewu2508** [comment]
The first three conv1d is successful, but at the 4th rocBLAS found the solution of called `Cijk_Ailk_Bljk_SB_MT32x32x2_SE_APM1_AF0EM1_AF1EM1_AMAS2_ASBE01_ASCE01_ASEM1_BL0_DTL0_EPS0_FL0_GRVW4_GSU1_ISA000_IU1_K1_KLS_LPA0_LPB0_LDL1_LRVW4_MDA2_NLCA1_NLCB1_ONLL1_PBD0_PK0_PGR1_PLR1_RK0_SU32_SUM0_SUS256_SVW4_SNLL0_TT4_4_USFGRO0_VAW1_VS1_VW4_WG8_8_1_WGM1`, which is included in `${EPREFIX}/usr/lib64/rocblas/library/TensileLibrary.dat` (tensile database). However the kernel of this solution is not found in `${EPREFIX}/usr/lib64/rocblas/library/TensileLibrary_gfx906.co` (code object, or fat binary).

So it seems that during the configuration of rocBLAS with tensile, the code object is not correctly generated , similar to https://github.com/justxi/rocm/issues/183

**Comment by xuhuisheng** [comment]
ISA000 related kernel should be in the Kernels.so-000-gfx906.hsaco

**Comment by littlewu2508** [comment]
> 
> 
> ISA000 related kernel should be in the Kernels.so-000-gfx906.hsaco

You're right. But the `Kernels.so-000-gfx906.hsaco` is missing for me due to https://github.com/justxi/rocm/issues/183.

After using rocblas4.0.0_2.32.0.2844-cc18d25f_amd64.deb to replace the gentoo package pytorch works fine. So https://github.com/justxi/rocm/issues/183 still exists and is breaking pytorch
